version: "3.7"
name: crm

services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      custom_net:
        ipv4_address: 172.28.0.2

  redis:
    image: redis:alpine
    networks:
      custom_net:
        ipv4_address: 172.28.0.3

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      custom_net:
        ipv4_address: 172.28.0.4

volumes:
  mariadb-data:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
